### ISSUE TITLE
Users without permission to use the extension shouldn't be allowed on special page

### ISSUE THREAD

**Issue by hexmode** [christi3k/ImportFromEtherpad#6]
I just imported a page successfully (http://mwstake.org/mwstake/index.php/Sandbox) after logging in.  But the first time I tried, I was able to visit http://mwstake.org/mwstake/index.php/Special:ImportFromEtherpad without the ability to actually use the page (I wasn't logged in).

Great tool, by the way.

**Comment by christi3k** [comment]
The extension checks to see if the user can create OR edit pages. It looks like anonymous users have createpage right on mwstake.org?

**Comment by hexmode** [comment]
No, createpage isn't allowed.  Try this link: http://mwstake.org/mwstake/wiki/Some-page?action=edit

**Comment by christi3k** [comment]
I'm looking here: http://mwstake.org/mwstake/wiki/Special:ListGroupRights where is says 'all' group has 'createpage' right. 

MW documentation says 'createpage' right requires 'edit' right but isn't clear on what to do when 'createpage' is assigned but 'edit' isn't. It seems permissible when checking whether or not to display the page to check for 'edit' right only since if a user is able to create they will also be able to edit. Later on we can check for edit vs createpage since I'd like users to be able to update existing pages if they have that right.

**Comment by hexmode** [comment]
Christie Koehler writes:

> MW documentation says 'createpage' right requires 'edit' right but
> isn't clear on what to do when 'createpage' is assigned but 'edit'
> isn't.

There should be a bug for this.  Could you file one?

Mark.

## 

Mark A. Hershberger
NicheWork LLC
717-271-1084
